import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECTS_DIR = path.join(__dirname, "projects");
const ENTITY_KINDS = ["characters", "places", "objects", "references"];

// Absolute (not relative) so these still resolve correctly for a browser loading the
// frontend from somewhere else entirely (a centrally-hosted UI) — "localhost" always
// means the browser's OWN machine, which is where this local backend actually runs, so
// this reaches the right place regardless of what origin served the page itself.
const LOCAL_ORIGIN = `http://localhost:${process.env.PORT || 8787}`;

fs.mkdirSync(PROJECTS_DIR, { recursive: true });

function readJSON(p) {
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, "utf-8"));
  } catch {
    return null;
  }
}
function writeJSON(p, data) {
  fs.writeFileSync(p, JSON.stringify(data, null, 2));
}

function slugify(name) {
  const slug = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return slug || "item";
}

// Turn a name into a unique folder name under `dir` (handles "alex", "alex-2", ...)
function uniqueSlug(dir, name) {
  const base = slugify(name);
  let slug = base;
  let n = 2;
  while (fs.existsSync(path.join(dir, slug))) {
    slug = `${base}-${n++}`;
  }
  return slug;
}

// ---------- Projects: ProjectName/ ----------

function projectDir(projectId) {
  return path.join(PROJECTS_DIR, projectId);
}

export function listProjects() {
  return fs
    .readdirSync(PROJECTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => readJSON(path.join(PROJECTS_DIR, d.name, "project.json")))
    .filter(Boolean)
    .sort((a, b) => a.createdAt - b.createdAt);
}

export function getProject(projectId) {
  return readJSON(path.join(projectDir(projectId), "project.json"));
}

export function createProject(name) {
  const id = uniqueSlug(PROJECTS_DIR, name);
  const dir = projectDir(id);
  fs.mkdirSync(dir, { recursive: true });
  for (const kind of ENTITY_KINDS) fs.mkdirSync(path.join(dir, kind), { recursive: true });

  const project = { id, name: name.trim(), createdAt: Date.now() };
  writeJSON(path.join(dir, "project.json"), project);
  writeJSON(path.join(dir, "pages.json"), []);
  return project;
}

export function deleteProject(projectId) {
  fs.rmSync(projectDir(projectId), { recursive: true, force: true });
}

// ---------- Characters / Places / Objects: ProjectName/<kind>/<slug>/ ----------
// Each entity folder holds: meta.json (source of truth), information.txt (human-readable
// mirror of meta.json), and image.png (once generated/uploaded).

function entityDir(projectId, kind, entityId) {
  return path.join(projectDir(projectId), kind, entityId);
}

function writeInformationTxt(dir, meta) {
  const lines = [`Name: ${meta.name}`];
  if (meta.style) lines.push(`Style: ${meta.style}`);
  for (const [key, value] of Object.entries(meta.fields || {})) {
    if (String(value ?? "").trim() === "") continue;
    lines.push(`${key.charAt(0).toUpperCase()}${key.slice(1)}: ${value}`);
  }
  fs.writeFileSync(path.join(dir, "information.txt"), lines.join("\n") + "\n");
}

// Exported (like panels' equivalent) so callers that need to hand Codex a direct save
// target — rather than routing the generated bytes through this module — can compute it.
export function entityImagePath(projectId, kind, entityId) {
  return path.join(entityDir(projectId, kind, entityId), "image.png");
}

function readEntity(projectId, kind, entityId) {
  const dir = entityDir(projectId, kind, entityId);
  const meta = readJSON(path.join(dir, "meta.json"));
  if (!meta) return null;
  return { ...meta, id: entityId, hasImage: fs.existsSync(entityImagePath(projectId, kind, entityId)) };
}

export function listEntities(projectId, kind) {
  const kindDir = path.join(projectDir(projectId), kind);
  if (!fs.existsSync(kindDir)) return [];
  return fs
    .readdirSync(kindDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => readEntity(projectId, kind, d.name))
    .filter(Boolean)
    .sort((a, b) => a.createdAt - b.createdAt);
}

export function getEntity(projectId, kind, entityId) {
  return readEntity(projectId, kind, entityId);
}

export function createEntity(projectId, kind, { name, fields = {}, style = "" }) {
  const kindDir = path.join(projectDir(projectId), kind);
  fs.mkdirSync(kindDir, { recursive: true });
  const id = uniqueSlug(kindDir, name);
  const dir = path.join(kindDir, id);
  fs.mkdirSync(dir, { recursive: true });

  const meta = { name: name.trim(), fields, style, createdAt: Date.now() };
  writeJSON(path.join(dir, "meta.json"), meta);
  writeInformationTxt(dir, meta);
  return { ...meta, id, hasImage: false };
}

export function updateEntity(projectId, kind, entityId, updates) {
  const dir = entityDir(projectId, kind, entityId);
  const meta = readJSON(path.join(dir, "meta.json"));
  if (!meta) return null;

  if (updates.name?.trim()) meta.name = updates.name.trim();
  if (updates.fields) meta.fields = { ...meta.fields, ...updates.fields };
  if (updates.style !== undefined) meta.style = updates.style;

  writeJSON(path.join(dir, "meta.json"), meta);
  writeInformationTxt(dir, meta);
  return { ...meta, id: entityId, hasImage: fs.existsSync(entityImagePath(projectId, kind, entityId)) };
}

export function deleteEntity(projectId, kind, entityId) {
  fs.rmSync(entityDir(projectId, kind, entityId), { recursive: true, force: true });
}

export function saveEntityImage(projectId, kind, entityId, buffer) {
  fs.writeFileSync(entityImagePath(projectId, kind, entityId), buffer);
}

export function loadEntityImage(projectId, kind, entityId) {
  const p = entityImagePath(projectId, kind, entityId);
  return fs.existsSync(p) ? fs.readFileSync(p) : null;
}

export function entityImageUrl(projectId, kind, entityId) {
  return `${LOCAL_ORIGIN}/projects/${projectId}/${kind}/${entityId}/image.png`;
}

// ---------- Pages: ProjectName/pages.json ----------

// Panels used to store characterIds/placeId/objectIds arrays plus a separate plain
// sceneDescription string. That's replaced by a single sceneDoc (rich text with
// inline #mentions — see scene.js). Migrate any panel still in the old shape by
// folding its selections into an equivalent doc, so existing pages keep their cast.
function migratePanel(projectId, panel) {
  if (panel.sceneDoc) return panel;

  const content = [];
  if (panel.sceneDescription?.trim()) content.push({ type: "text", text: panel.sceneDescription.trim() + " " });

  const mentionsFor = (kind, ids) => {
    for (const id of ids ?? []) {
      const entity = getEntity(projectId, kind, id);
      if (entity) content.push({ type: "mention", attrs: { id: `${kind}:${id}`, label: entity.name } }, { type: "text", text: " " });
    }
  };
  mentionsFor("characters", panel.characterIds);
  mentionsFor("places", panel.placeId ? [panel.placeId] : []);
  mentionsFor("objects", panel.objectIds);

  const { characterIds, placeId, objectIds, sceneDescription, ...rest } = panel;
  return { ...rest, sceneDoc: { type: "doc", content: [{ type: "paragraph", content }] } };
}

export function listPages(projectId) {
  const pages = readJSON(path.join(projectDir(projectId), "pages.json")) || [];
  let migrated = false;
  for (const page of pages) {
    page.panels = page.panels.map((panel) => {
      if (panel.sceneDoc) return panel;
      migrated = true;
      return migratePanel(projectId, panel);
    });
    for (const panel of page.panels) migratePanelImage(projectId, page.id, panel);
  }
  if (migrated) savePages(projectId, pages);
  return pages;
}
export function savePages(projectId, pages) {
  writeJSON(path.join(projectDir(projectId), "pages.json"), pages);
}

// ---------- Panel images: ProjectName/pages/<pageId>/panels/<panelId>/image.png ----------
// Mirrors the character/place/object folder convention above — a panel's own JSON data
// (order, scene text, bubbles, crop/rotate/zoom) still lives in pages.json, but its
// rendered/uploaded image now gets a real per-panel folder instead of the old flat,
// unsorted uploads/ bucket every project's every panel used to share.

const LEGACY_UPLOAD_DIR = path.join(__dirname, "uploads");

function panelImageDir(projectId, pageId, panelId) {
  return path.join(projectDir(projectId), "pages", pageId, "panels", panelId);
}
// Exported (unlike entities' equivalent) because open-image needs the raw path to shell
// out to the OS's "reveal this file" command — everything else just needs save/load/delete.
export function panelImagePath(projectId, pageId, panelId) {
  return path.join(panelImageDir(projectId, pageId, panelId), "image.png");
}

// Self-healing, one-time-per-panel migration: older panels point at a flat
// uploads/<id>.png file via the now-retired imageAssetId field. The first time such a
// panel is read, move its image into the new per-panel folder — no separate migration
// script for anyone to remember to run. This MOVES rather than copies: imageAssetId is
// never cleared once a panel is migrated (nothing writes to it anymore), so if the
// legacy file were left in place, deleting the image later would make this same
// migration step silently resurrect it from that legacy copy on the next page load.
// Consuming the legacy file on first migration closes that off.
function migratePanelImage(projectId, pageId, panel) {
  if (!panel.imageAssetId) return;
  const dest = panelImagePath(projectId, pageId, panel.id);
  if (fs.existsSync(dest)) return;
  const legacySrc = path.join(LEGACY_UPLOAD_DIR, `${panel.imageAssetId}.png`);
  if (!fs.existsSync(legacySrc)) return;
  fs.mkdirSync(panelImageDir(projectId, pageId, panel.id), { recursive: true });
  try {
    fs.renameSync(legacySrc, dest);
  } catch {
    // Cross-device (EXDEV) or similar — fall back to copy then remove the source.
    fs.copyFileSync(legacySrc, dest);
    fs.unlinkSync(legacySrc);
  }
}

export function savePanelImage(projectId, pageId, panelId, buffer) {
  const dir = panelImageDir(projectId, pageId, panelId);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(panelImagePath(projectId, pageId, panelId), buffer);
}

export function loadPanelImage(projectId, pageId, panelId) {
  const p = panelImagePath(projectId, pageId, panelId);
  return fs.existsSync(p) ? fs.readFileSync(p) : null;
}

export function deletePanelImage(projectId, pageId, panelId) {
  fs.rmSync(panelImageDir(projectId, pageId, panelId), { recursive: true, force: true });
}

// mtime doubles as a free cache-buster — every save/regenerate overwrites the file,
// which bumps mtime automatically, so the browser always refetches the new image
// without needing a separate version counter persisted in pages.json.
export function panelImageInfo(projectId, pageId, panelId) {
  const p = panelImagePath(projectId, pageId, panelId);
  if (!fs.existsSync(p)) return { hasImage: false, imageUrl: null };
  const v = Math.round(fs.statSync(p).mtimeMs);
  return {
    hasImage: true,
    imageUrl: `${LOCAL_ORIGIN}/projects/${projectId}/pages/${pageId}/panels/${panelId}/image.png?v=${v}`,
  };
}
